# ==========================================
# CONFIGURAÇÕES DO SERVIDOR
# ==========================================
server.port=8080

# ==========================================
# CONFIGURAÇÕES DO BANCO DE DADOS (PostgreSQL)
# ==========================================
spring.datasource.url=jdbc:postgresql://localhost:5432/api_spring
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# ==========================================
# CONFIGURAÇÕES DO JPA / HIBERNATE
# ==========================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ==========================================
# CONFIGURAÇÕES DO SPRING
# ==========================================
spring.application.name=api_sistema_academico

# ==========================================
# CONFIGURAÇÕES DE LOG
# ==========================================
logging.level.org.springframework=INFO
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql=TRACE

# ==========================================
# CONFIGURAÇÕES DE SERIALIZAÇÃO JSON
# ==========================================
spring.jackson.serialization.fail-on-empty-beans=false
spring.jackson.deserialization.fail-on-unknown-properties=false
